apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.images.frontend }}
        ports:
        - containerPort: 5175
        env:
        - name: BACKEND_URL
          value: {{ .Values.env.frontend.BACKEND_URL }}
