apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: {{ .Values.services.frontend.type }}
  ports:
  - port: {{ .Values.services.frontend.port }}
    nodePort: {{ .Values.services.frontend.nodePort }}
    targetPort: 5175
  selector:
    app: frontend
