replicaCount: 1

images:
  backend: shreybatra/sample-backend
  frontend: shreybatra/sample-frontend
  redis: redis

env:
  backend:
    REDIS_URI: redis://redis-svc:6379
  frontend:
    BACKEND_URL: http://backend-svc:8000

services:
  backend:
    type: ClusterIP
    port: 8000
  frontend:
    type: NodePort
    port: 5175
    nodePort: 31000
  redis:
    type: ClusterIP
    port: 6379
